language: cpp
sudo: false
dist: trusty
compiler:
- clang
- gcc
env:
- EIGEN=3.2.10
- EIGEN=3.3.3

# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - gcc-5
#     - g++-5
# 
# before_install:
# # Set compiler version
# - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

install:
# Install Eigen from source
- wget https://bitbucket.org/eigen/eigen/get/$EIGEN.tar.bz2 -O /tmp/eigen.tar.bz2
- mkdir eigen3-src && tar -xvjf /tmp/eigen.tar.bz2 -C eigen3-src --strip-components 1
- mkdir -p $HOME/eigen
- cd eigen3-src && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$HOME/eigen .. && make install && cd ../..

script:
- mkdir build
- cd build
- cmake -DCMAKE_PREFIX_PATH=$HOME/eigen .. && make
- ./kalman_test
