language: cpp
sudo: false
dist: trusty
compiler:
- clang
- gcc
env:
- EIGEN=3.2.10
- EIGEN=3.3.4

# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - gcc-5
#     - g++-5
# 
# before_install:
# # Set compiler version
# - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

before_install:
  - bash travis_install.sh

cache:
  directories:
  - $HOME/eigen

script:
- mkdir build
- cd build
- cmake -DCMAKE_PREFIX_PATH=$HOME/eigen/$EIGEN .. && make
- ./kalman_test
